site_name: ⚡ Energy Monitor Ultimate
repo_url: https://github.com/Lutvunenko-Dmutro/EnergyMonitor-OLAP
edit_uri: edit/main/docs/

theme:
  name: material  # Найкраща тема для GitHub
  palette:
    scheme: slate # Темна тема (виглядає солідно)
    primary: deep orange
  features:
    - navigation.tabs # Зручні вкладки зверху

plugins:
  - search
  - mkdocstrings: # Плагін для авто-конспекту з коду
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")