import os

import pandas as pd
import psycopg2
from dotenv import load_dotenv
from psycopg2.extras import execute_values

# Завантажуємо конфігурацію БД
load_dotenv()
from src.core.config import DB_CONFIG


def import_real_data(csv_path="AEP_hourly.csv"):
    """
    Зчитує реальні дані з CSV (формат: Datetime, AEP_MW)
    і заливає їх у нову ізольованую таблицю.
    """
    print("⏳ Очищення та зчитування CSV...")

    if not os.path.exists(csv_path):
        print(f"❌ Файл {csv_path} не знайдено!")
        return

    # Читаємо датасет: pandas сам визначить типи
    df = pd.read_csv(csv_path)

    # Конвертуємо час у правильний формат і сортуємо в хронологічному порядку
    df["Datetime"] = pd.to_datetime(df["Datetime"])
    df = df.sort_values("Datetime")

    # Видаляємо дублікати (якщо є) щоб уникнути помилок
    df = df.drop_duplicates(subset=["Datetime"])

    print(f"✅ Зчитано {len(df)} записів. Підключення до бази...")

    try:
        conn = psycopg2.connect(**DB_CONFIG)
        cursor = conn.cursor()

        # 1. СТВОРЕННЯ ТАБЛИЦІ (якщо немає)
        # Синтетичні дані (LoadMeasurements) ми НЕ чіпаємо!
        print("🏗️ Перевірка таблиці RealLoadMeasurements...")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS RealLoadMeasurements (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                timestamp TIMESTAMPTZ NOT NULL UNIQUE,
                actual_load_mw DECIMAL(10, 2) NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_real_load_ts ON RealLoadMeasurements(timestamp);
        """)

        # Можемо очистити реальні дані перед новим заливанням (опціонально)
        # cursor.execute("TRUNCATE TABLE RealLoadMeasurements;")

        # 2. ПІДГОТОВКА ДАНИХ ДЛЯ ІНСЕРТУ
        # psycopg2.extras.execute_values очікує список кортежів (list of tuples)
        data_tuples = list(
            df[["Datetime", "AEP_MW"]].itertuples(index=False, name=None)
        )

        # 3. ВСТАВКА
        print("💾 Масовий запис даних (Batch Insert)... Це може зайняти хвилину-дві.")

        # ON CONFLICT DO NOTHING дозволяє безпечно перезапускати скрипт без помилок про дублікати
        query = """
            INSERT INTO RealLoadMeasurements (timestamp, actual_load_mw) 
            VALUES %s 
            ON CONFLICT (timestamp) DO NOTHING;
        """

        execute_values(cursor, query, data_tuples)

        conn.commit()
        print("🎉 Імпорт успішно завершено! Дані готові до використання в ML та UI.")

    except Exception as e:
        if conn:
            conn.rollback()
        print(f"❌ Помилка бази даних: {e}")
    finally:
        if conn:
            cursor.close()
            conn.close()


if __name__ == "__main__":
    import_real_data()
