DROP TABLE IF EXISTS EnergyPricing CASCADE;
DROP TABLE IF EXISTS MaintenanceEvents CASCADE;
DROP TABLE IF EXISTS Alerts CASCADE;
DROP TABLE IF EXISTS WeatherReports CASCADE;
DROP TABLE IF EXISTS GenerationMeasurements CASCADE;
DROP TABLE IF EXISTS LineMeasurements CASCADE;
DROP TABLE IF EXISTS LoadMeasurements CASCADE;
DROP TABLE IF EXISTS Generators CASCADE;
DROP TABLE IF EXISTS Consumers CASCADE;
DROP TABLE IF EXISTS PowerLines CASCADE;
DROP TABLE IF EXISTS Substations CASCADE;
DROP TABLE IF EXISTS Regions CASCADE;

-- =========================================================
-- MODULE 1: ДОВІДНИКИ (STATIC DATA)
-- =========================================================

CREATE TABLE Regions (
    region_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    region_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Substations (
    substation_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    substation_name VARCHAR(150) NOT NULL,
    location VARCHAR(255),
    capacity_mw DECIMAL(10, 2) NOT NULL CHECK (capacity_mw > 0),
    region_id INT,
    latitude DECIMAL(9, 6),
    longitude DECIMAL(10, 6),
    FOREIGN KEY (region_id) REFERENCES Regions(region_id) ON DELETE SET NULL
);
CREATE INDEX idx_sub_region_id ON Substations(region_id);

CREATE TABLE PowerLines (
    line_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    line_name VARCHAR(100),
    max_load_mw DECIMAL(10, 2) NOT NULL CHECK (max_load_mw > 0),
    from_substation_id INT,
    to_substation_id INT,
    FOREIGN KEY (from_substation_id) REFERENCES Substations(substation_id) ON DELETE SET NULL,
    FOREIGN KEY (to_substation_id) REFERENCES Substations(substation_id) ON DELETE SET NULL,
    -- Захист від циклів 
    CHECK (from_substation_id <> to_substation_id)
);
CREATE INDEX idx_pl_from_sub ON PowerLines(from_substation_id);
CREATE INDEX idx_pl_to_sub ON PowerLines(to_substation_id);

CREATE TABLE Consumers (
    consumer_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    consumer_name VARCHAR(150) NOT NULL,
    consumer_type VARCHAR(50) CHECK (consumer_type IN ('промисловий', 'побутовий', 'комерційний', 'інший')),
    substation_id INT,
    FOREIGN KEY (substation_id) REFERENCES Substations(substation_id) ON DELETE SET NULL
);
CREATE INDEX idx_con_substation_id ON Consumers(substation_id);

CREATE TABLE Generators (
    generator_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    generator_type VARCHAR(50) NOT NULL CHECK (generator_type IN ('solar', 'thermal', 'wind', 'hydro', 'nuclear', 'інший')),
    max_output_mw DECIMAL(10, 2) NOT NULL CHECK (max_output_mw > 0),
    substation_id INT,
    FOREIGN KEY (substation_id) REFERENCES Substations(substation_id) ON DELETE SET NULL
);
CREATE INDEX idx_gen_substation_id ON Generators(substation_id);

-- =========================================================
-- MODULE 2: ЖУРНАЛИ ВИМІРЮВАНЬ (TIME-SERIES DATA)
-- =========================================================

CREATE TABLE LoadMeasurements (
    measurement_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMPTZ NOT NULL,
    actual_load_mw DECIMAL(10, 2) NOT NULL,
    substation_id INT,
    FOREIGN KEY (substation_id) REFERENCES Substations(substation_id) ON DELETE CASCADE
);
-- Композитний індекс для швидкого пошуку графіків по підстанції
CREATE INDEX idx_load_ts_sub ON LoadMeasurements (substation_id, timestamp);

CREATE TABLE LineMeasurements (
    line_measurement_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMPTZ NOT NULL,
    actual_load_mw DECIMAL(10, 2) NOT NULL,
    line_id INT,
    FOREIGN KEY (line_id) REFERENCES PowerLines(line_id) ON DELETE CASCADE
);
CREATE INDEX idx_line_ts_id ON LineMeasurements(line_id, timestamp);

CREATE TABLE GenerationMeasurements (
    gen_measurement_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMPTZ NOT NULL,
    actual_generation_mw DECIMAL(10, 2) NOT NULL,
    generator_id INT,
    FOREIGN KEY (generator_id) REFERENCES Generators(generator_id) ON DELETE CASCADE
);
CREATE INDEX idx_gen_ts_id ON GenerationMeasurements(generator_id, timestamp);

-- =========================================================
-- MODULE 3: АНАЛІТИКА ТА ПОДІЇ (EVENTS & ANALYTICS)
-- =========================================================

CREATE TABLE WeatherReports (
    timestamp TIMESTAMPTZ NOT NULL,
    region_id INT NOT NULL,
    temperature DECIMAL(5, 2),
    conditions VARCHAR(50),
    -- Композитний первинний ключ (в одному регіоні в один час одна погода)
    PRIMARY KEY (timestamp, region_id),
    FOREIGN KEY (region_id) REFERENCES Regions(region_id) ON DELETE CASCADE
);

CREATE TABLE Alerts (
    alert_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMPTZ NOT NULL,
    alert_type VARCHAR(100) NOT NULL,
    description TEXT,
    substation_id INT,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW' CHECK (status IN ('NEW', 'ACKNOWLEDGED', 'RESOLVED')),
    FOREIGN KEY (substation_id) REFERENCES Substations(substation_id) ON DELETE SET NULL
);
CREATE INDEX idx_alert_ts_sub ON Alerts(timestamp, substation_id);
CREATE INDEX idx_alert_status ON Alerts(status);

CREATE TABLE MaintenanceEvents (
    event_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    object_id INT NOT NULL,
    object_type VARCHAR(20) NOT NULL CHECK (object_type IN ('Підстанція', 'Лінія')),
    reason VARCHAR(255),
    -- Перевірка хронології
    CHECK (end_time > start_time)
);
CREATE INDEX idx_maint_time ON MaintenanceEvents(start_time, end_time);

CREATE TABLE EnergyPricing (
    timestamp TIMESTAMPTZ NOT NULL,
    region_id INT NOT NULL,
    price_per_mwh DECIMAL(10, 2) NOT NULL CHECK (price_per_mwh >= 0),
    PRIMARY KEY (timestamp, region_id),
    FOREIGN KEY (region_id) REFERENCES Regions(region_id) ON DELETE CASCADE
);
